"""
provenance.py: Where every value of a graph comes from, as a graph.

A graph carries a number. That it was read on page 97, from which words,
by which run and how far the run stands behind it, the harvest knows and
the graph does not say. This module says it, in a file of its own beside
the graph (`<graph>.prov.ttl`), with PROV-O and the W3C Web Annotation
vocabulary and a small vocabulary for what those two do not have. Every
statement points at a value and none starts from one, so the graph itself
is the same with and without it, and a reader who does not want it leaves
the file away. A run that should not write it is started with
EXTRACT_PROVENANCE=0.

Per value:

    its reading       an oa:Annotation whose body is the value and whose
                      target is the part of the document it stands in: the
                      page (a fragment selector), refined by the quote and,
                      where the quote was located, by its rectangles
    each coordinate   an annotation of its own: what was read (the body),
                      the wording it was read from, how the reading ended,
                      and its own passage where it had one; generated by
                      the run, or by the pass (a top-up, with its own model
                      and time) the coordinate's `<axis>_producer` points at
    its trust         an assessment with the level, the reasons below A and
                      whether it was read from an image
    a second reading  what it came to, where one was made
    a decision        what a person decided about one of its fields, where
                      someone did: correct or wrong, who, when and the note.
                      Kept beside the value, which stays as it is

and once per document the run (a prov:Activity with its model and the
fingerprints of the spec and the prompts) and each part of the document
that is quoted.

The vocabulary's terms live where the writer says (`vocabulary`: a prefix
and an IRI). A graph that has an ontology for them names it; one that has
none gets them under its own base.

Not written yet: the decision between two readings that claim one value.
The writers settle that before a value reaches this module, and what lost
does not come with it. A decision of a person is not that: it is recorded
and judges nothing.

Author: Felix Vossel
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Optional
from urllib.parse import quote

from . import fields, identity, trust
from .graphkit import NOT_IN_GRAPH, ttl_string

SWITCH = "EXTRACT_PROVENANCE"
SUFFIX = ".prov.ttl"

PREFIXES = {
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "dcterms": "http://purl.org/dc/terms/",
    "prov": "http://www.w3.org/ns/prov#",
    "oa": "http://www.w3.org/ns/oa#",
    "doco": "http://purl.org/spar/doco/",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
}
PARTS = {"section": "doco:Section", "table": "doco:Table",
         "figure": "doco:Figure"}
PAGE_FRAGMENT = "http://tools.ietf.org/rfc/rfc3778"
MEDIA_FRAGMENT = "http://www.w3.org/TR/media-frags/"

# The terms of the vocabulary, each with what it means. One table, read
# for the header of the file and for the names the triples use, so a term
# cannot be used that is not defined.
CLASSES = {
    "TrustAssessment": ("prov:Entity", "How far a run stands behind a "
                        "value: a level and, below A, the reasons."),
    "Review": ("prov:Entity", "What a second reading of a value came to. "
               "It never raises a level."),
    "Decision": ("prov:Entity", "What a person decided about one field of a "
                 "value: correct or wrong. It is kept beside the value and "
                 "changes nothing about it."),
}
OBJECT_PROPERTIES = {
    "about": "Links an annotation, an assessment or a review to the value "
             "it is about. Always points at the value, never from it.",
    "readingState": "How a coordinate's reading ended; a concept of "
                    "ReadingState.",
    "outsideVocabulary": "The coordinate was read, and what was read is "
                         "deliberately no class of the vocabulary (a "
                         "total, an other); the annotation then has no "
                         "body.",
    "mappedBy": "Who assigned the wording to the class in the body.",
    "readingNote": "A note on the reading; a concept of ReadingNote.",
    "trustLevel": "A concept of TrustLevel.",
    "trustReason": "A concept of TrustReason.",
    "reviewOutcome": "A concept of ReviewOutcome.",
}
DATA_PROPERTIES = {
    "coordinate": "Which statement the annotation backs: value, or the "
                  "name of a coordinate.",
    "wording": "The words of the document the reading rests on.",
    "rawForeign": "The wording is none of the spellings the vocabulary "
                  "lists for the chosen class: the assignment is an "
                  "interpretation, not a recognition.",
    "fromImage": "Read from a table or a figure a model transcribed from "
                 "its image.",
    "specFingerprint": "Checksum of the extraction spec a run worked with.",
    "promptHash": "Checksum of the instructions a run gave its model.",
}
# A concept has one meaning and may stand in several schemes: a coordinate
# that was left open is a reading state and, for the value, a reason.
CONCEPTS = {
    fields.READ: "Answered, and the quoted passage carries the answer.",
    fields.DERIVED: "Not asked: it follows from another coordinate.",
    fields.SAID_UNSTATED: "Answered: the document does not say it. A "
                          "statement about the document.",
    fields.UNANSWERED: "The model never answered. A statement about the "
                       "model.",
    fields.EXHAUSTED: "Still open when the reading stopped before the "
                      "document was read to its end. A statement about the "
                      "run.",
    fields.UNBACKED: "Answered, and no passage carried the answer.",
    "total": "The sum over every entry of the list.",
    "other": "A remainder with no class of its own.",
    "period_unstated": "The unit names no period although the quantity "
                       "needs one.",
    "quote_repaired": "The quote differed from the wording of the source "
                      "and was brought into line with it.",
    trust.LEVEL_A: "Stated in the document's own text, every coordinate "
                   "read or derived.",
    trust.LEVEL_B: "As A, but read from an image a model transcribed, or "
                   "from a document without a text layer.",
    trust.LEVEL_C: "Something is open; the reasons say what.",
    "page_transcribed": "The document had no text layer; a model "
                        "transcribed its pages.",
    "repaired": "The value's quote had to be brought into line with the "
                "source.",
    "computed": "The value does not stand in the document; it was computed "
                "from values that do.",
    "not_located": "The quote could not be located on the page.",
    "conflict": "Another reading claims the same value with another "
                "number.",
    "agree": "A second reading came to the same value.",
    "disagree": "A second reading came to another value.",
}
SCHEMES = {
    "ReadingState": (fields.READ, fields.DERIVED, fields.SAID_UNSTATED,
                     fields.UNANSWERED, fields.EXHAUSTED, fields.UNBACKED),
    "OutsideVocabulary": ("total", "other"),
    "ReadingNote": ("period_unstated", "quote_repaired"),
    "TrustLevel": (trust.LEVEL_A, trust.LEVEL_B, trust.LEVEL_C),
    "TrustReason": ("page_transcribed", fields.EXHAUSTED, fields.UNBACKED,
                    fields.UNANSWERED, "repaired", "computed",
                    "not_located", "disagree", "conflict"),
    "ReviewOutcome": ("agree", "disagree", fields.UNBACKED),
}
_REASON = {"repaired": "repaired", "computed": "computed",
           "not_located": "not_located", "conflict": "conflict",
           "page_transcribed": "page_transcribed",
           trust.REVIEW_DISAGREE: "disagree"}
_REVIEW = {trust.REVIEW_AGREE: "agree", trust.REVIEW_DISAGREE: "disagree",
           trust.REVIEW_UNBACKED: fields.UNBACKED}
_NOTE = {"quote_repaired": "quote_repaired",
         "period:unstated": "period_unstated"}
OUT = NOT_IN_GRAPH
# What xsd:dateTime spells; a time a person typed that is none stays a string.
_DATE_TIME = re.compile(r"-?\d{4,}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?"
                        r"(Z|[+-]\d{2}:\d{2})?")


def enabled() -> bool:
    return (os.environ.get(SWITCH) or "1").strip().lower() \
        not in ("0", "false", "no", "off")


def path_for(graph_path) -> Path:
    graph_path = Path(graph_path)
    return graph_path.with_name(graph_path.stem + SUFFIX)


def _reason_term(reason: str) -> Optional[str]:
    """The concept a trust reason is. `exhausted:year` is the reason
    `exhausted`: which coordinate it was is said by the link to that
    coordinate's annotation."""
    if reason in _REASON:
        return _REASON[reason]
    state = reason.split(":", 1)[0]
    if state in (fields.EXHAUSTED, fields.UNBACKED, fields.UNANSWERED):
        return state
    return None


class Writer:
    """Collects the provenance of a run's values and writes it once."""

    def __init__(self, base: str, vocabulary: Optional[dict] = None):
        if not base or base[-1] not in "/#":
            raise ValueError(f"provenance base {base!r} must end in / or #")
        self.base = base
        vocabulary = vocabulary or {}
        self.prefix = vocabulary.get("prefix") or "dpx"
        self.namespace = vocabulary.get("iri") or f"{base}prov/vocabulary#"
        if self.prefix in PREFIXES:
            raise ValueError(f"provenance prefix {self.prefix!r} is taken")
        self.parts: list = []
        self.documents = self.values = 0
        # Decisions of people recorded beside a value.
        self.decisions = 0
        self._agents: set = set()

    # ----------------------------------------------------------- the terms

    def term(self, name: str) -> str:
        known = (name in CLASSES or name in OBJECT_PROPERTIES
                 or name in DATA_PROPERTIES or name in SCHEMES
                 or name in CONCEPTS)
        if not known:
            raise KeyError(f"{name!r} is not a term of the vocabulary")
        return f"<{self.namespace}{name}>"

    def header(self) -> str:
        lines = [f"@prefix {prefix}: <{iri}> ."
                 for prefix, iri in PREFIXES.items()]
        lines += [f"@prefix {self.prefix}: <{self.namespace}> .", ""]
        for name, (parent, meaning) in CLASSES.items():
            lines.append(f"{self.term(name)} a owl:Class ; rdfs:subClassOf "
                         f"{parent} ; rdfs:comment {ttl_string(meaning)}@en .")
        for name, meaning in OBJECT_PROPERTIES.items():
            lines.append(f"{self.term(name)} a owl:ObjectProperty ; "
                         f"rdfs:comment {ttl_string(meaning)}@en .")
        for name, meaning in DATA_PROPERTIES.items():
            lines.append(f"{self.term(name)} a owl:DatatypeProperty ; "
                         f"rdfs:comment {ttl_string(meaning)}@en .")
        for scheme in SCHEMES:
            lines.append(f"{self.term(scheme)} a skos:ConceptScheme .")
        for name, meaning in CONCEPTS.items():
            schemes = " , ".join(self.term(scheme) for scheme, names
                                 in SCHEMES.items() if name in names)
            lines.append(
                f"{self.term(name)} a skos:Concept ; "
                f"skos:inScheme {schemes} ; "
                f"skos:prefLabel {ttl_string(name)}@en ; "
                f"skos:definition {ttl_string(meaning)}@en .")
        return "\n".join(lines) + "\n"

    # --------------------------------------------------------- one document

    def _iri(self, *segments) -> str:
        return self.base + "prov/" + "/".join(
            quote(str(segment), safe="") for segment in segments)

    def _target(self, part: Optional[str], page, quote_text,
                rects=None) -> Optional[str]:
        """An oa:SpecificResource as a blank node, or None when nothing
        says where."""
        if part is None and not quote_text:
            return None
        exact = (f"[ a oa:TextQuoteSelector ; oa:exact "
                 f"{ttl_string(quote_text)} ]" if quote_text else None)
        boxes = []
        for rect in rects or ():
            try:
                x0, y0, x1, y1 = (float(rect[key]) for key in
                                  ("x0", "y0", "x1", "y1")) \
                    if isinstance(rect, dict) else map(float, rect[:4])
            except (KeyError, TypeError, ValueError):
                continue
            boxes.append(
                f"[ a oa:FragmentSelector ; dcterms:conformsTo "
                f"<{MEDIA_FRAGMENT}> ; rdf:value "
                f"\"xywh={x0:g},{y0:g},{x1 - x0:g},{y1 - y0:g}\" ]")
        lines = ["[ a oa:SpecificResource"]
        if part is not None:
            lines.append(f"        ; oa:hasSource <{part}>")
        if isinstance(page, int) and not isinstance(page, bool):
            refined = "".join(f" ; oa:refinedBy {selector}"
                              for selector in ([exact] if exact else [])
                              + boxes)
            lines.append(
                f"        ; oa:hasSelector [ a oa:FragmentSelector ; "
                f"dcterms:conformsTo <{PAGE_FRAGMENT}> ; rdf:value "
                f"\"page={page}\"{refined} ]")
        elif exact:
            lines.append(f"        ; oa:hasSelector {exact}")
        return "\n".join(lines) + " ]"

    def _decision(self, name: str, tuple_name: str, about: str,
                  decision: dict) -> str:
        """One person's decision on one field of a value, as a node of its
        own that points at the value."""
        field = decision["field"]
        lines = [f"<{self._iri('decision', name, tuple_name, field)}> a "
                 f"{self.term('Decision')}",
                 f"    ; {self.term('about')} <{about}>",
                 f"    ; {self.term('coordinate')} {ttl_string(field)}",
                 f"    ; rdf:value {ttl_string(decision['verdict'])}"]
        if decision.get("by"):
            lines.append(f"    ; dcterms:creator {ttl_string(decision['by'])}")
        if decision.get("at"):
            when = ttl_string(decision["at"])
            if _DATE_TIME.fullmatch(str(decision["at"])):
                when += "^^xsd:dateTime"
            lines.append(f"    ; dcterms:created {when}")
        if decision.get("note"):
            lines.append(f"    ; rdfs:comment {ttl_string(decision['note'])}")
        return "\n".join(lines) + " ."

    def add(self, name: str, claims: dict, stamp: Optional[dict] = None,
            *, transcribed: bool = False,
            decisions: Optional[dict] = None) -> None:
        """The provenance of one document's written values.

        *claims* is what a writer left for the document: `document` (the
        IRI of its node) and `values`, each with `about` (the IRI of the
        value), its harvest `row`, and optionally `id`, `bodies` (the IRI a
        coordinate became) and `statement` (subject, predicate, object as
        Turtle) where the value is a statement and not a node.

        *decisions* are what people decided about the document's rows,
        {tuple name: [decision]} as `gold.decisions_in` gives them. A value
        whose `id` they name gets each of its decisions recorded, counted in
        `decisions`; one the writer was handed no value for gets none.
        """
        values = claims.get("values") or []
        if not values:
            return
        document = claims["document"]
        stamp = stamp or {}
        producers = stamp.get("producers") or []
        model = stamp.get("model") or next(
            (entry.get("model") for entry in producers
             if entry.get("model")), None)
        out = []
        run = self._iri("run", name)
        agent = None
        if model:
            agent = self._iri("agent", model)
            if agent not in self._agents:
                self._agents.add(agent)
                out.append(f"<{agent}> a prov:SoftwareAgent ; rdfs:label "
                           f"{ttl_string(model)} .")
        lines = [f"<{run}> a prov:Activity", f"    ; prov:used <{document}>"]
        if agent:
            lines.append(f"    ; prov:wasAssociatedWith <{agent}>")
        ended = [entry.get("utc") for entry in producers if entry.get("utc")]
        if ended:
            lines.append(f"    ; prov:startedAtTime "
                         f"{ttl_string(min(ended))}^^xsd:dateTime")
            lines.append(f"    ; prov:endedAtTime "
                         f"{ttl_string(max(ended))}^^xsd:dateTime")
        if stamp.get("spec"):
            lines.append(f"    ; {self.term('specFingerprint')} "
                         f"{ttl_string('sha256:' + str(stamp['spec']))}")
        prompts = {key: value for key, value in sorted(stamp.items())
                   if key.startswith("prompt")}
        if prompts:
            digest = hashlib.sha256(json.dumps(
                prompts, sort_keys=True).encode("utf-8")).hexdigest()
            lines.append(f"    ; {self.term('promptHash')} "
                         f"{ttl_string('sha256:' + digest)}")
        generated = sorted({value["about"] for value in values})
        lines.append("    ; prov:generated "
                     + " ,\n        ".join(f"<{iri}>" for iri in generated))
        out.append("\n".join(lines) + " .")

        # The pass a coordinate points at (`fields.reader_of`), written once
        # per document and only where a coordinate does. The run above is the
        # harvest and what no coordinate says otherwise; a pass that re-read
        # a coordinate is its own activity, with its own model and time.
        passes: dict = {}

        def pass_of(index: int, entry: dict) -> tuple:
            """(activity IRI, agent IRI or None) of one entry of the list."""
            who = None
            if entry.get("model"):
                who = self._iri("agent", entry["model"])
                if who not in self._agents:
                    self._agents.add(who)
                    out.append(f"<{who}> a prov:SoftwareAgent ; rdfs:label "
                               f"{ttl_string(entry['model'])} .")
            iri = self._iri("run", name, f"producer-{index}")
            if index not in passes:
                passes[index] = (iri, who)
                node = [f"<{iri}> a prov:Activity"]
                if entry.get("pass"):
                    node.append(f"    ; rdfs:label {ttl_string(entry['pass'])}")
                node.append(f"    ; prov:used <{document}>")
                if who:
                    node.append(f"    ; prov:wasAssociatedWith <{who}>")
                if entry.get("utc"):
                    node.append(f"    ; prov:endedAtTime "
                                f"{ttl_string(entry['utc'])}^^xsd:dateTime")
                if entry.get("prompts"):
                    digest = hashlib.sha256(json.dumps(
                        entry["prompts"], sort_keys=True).encode(
                            "utf-8")).hexdigest()
                    node.append(f"    ; {self.term('promptHash')} "
                                f"{ttl_string('sha256:' + digest)}")
                out.append("\n".join(node) + " .")
            return passes[index]

        parts_written: set = set()

        def part_of(kind, owner, title=None, image=None) -> Optional[str]:
            if kind not in PARTS or owner is None:
                return None
            iri = self._iri("part", name, f"{kind}-{owner}")
            if iri not in parts_written:
                parts_written.add(iri)
                part = [f"<{iri}> a {PARTS[kind]}",
                        f"    ; dcterms:identifier "
                        f"{ttl_string(f'{kind}/{owner}')}",
                        f"    ; dcterms:isPartOf <{document}>"]
                if title:
                    part.append(f"    ; dcterms:title {ttl_string(title)}")
                if image:
                    part.append(f"    ; foaf:depiction {ttl_string(image)}")
                out.append("\n".join(part) + " .")
            return iri

        seen: dict = {}
        decided = decisions or {}
        taken: set = set()
        for value in values:
            row = value["row"]
            about = value["about"]
            tuple_name = value.get("id") or identity.tuple_id(name, row)
            asked = tuple_name
            seen[tuple_name] = seen.get(tuple_name, 0) + 1
            if seen[tuple_name] > 1:
                tuple_name = f"{tuple_name}.{seen[tuple_name]}"
            provenance = row.get("provenance") or {}
            statement = value.get("statement")
            if statement:
                subject, predicate, said = statement
                out.append(f"<{about}> a rdf:Statement ; rdf:subject "
                           f"<{subject}> ; rdf:predicate <{predicate}> ; "
                           f"rdf:object {said} .")
            here = part_of(provenance.get("owner_kind"),
                           provenance.get("owner_id"),
                           provenance.get("title")
                           or provenance.get("section_title"),
                           provenance.get("image"))
            annotation = self._iri("annotation", name, tuple_name, "value")
            lines = [f"<{annotation}> a oa:Annotation",
                     f"    ; oa:hasBody <{about}>",
                     f"    ; {self.term('about')} <{about}>",
                     f"    ; {self.term('coordinate')} \"value\"",
                     f"    ; prov:wasGeneratedBy <{run}>"]
            target = self._target(here, provenance.get("page"),
                                  row.get("quote"), provenance.get("rects"))
            if target:
                lines.append(f"    ; oa:hasTarget {target}")
            for flag in row.get("flags") or ():
                if flag in _NOTE:
                    lines.append(f"    ; {self.term('readingNote')} "
                                 f"{self.term(_NOTE[flag])}")
            out.append("\n".join(lines) + " .")

            bodies = value.get("bodies") or {}
            for axis in sorted(key[:-len("_state")] for key in row
                               if key.endswith("_state")):
                state = row.get(f"{axis}_state")
                # The harvest (no key), the pass the key points at, or
                # nobody that can be named: a position the list has no entry
                # for says nothing, and is not the harvest.
                who, index, entry = fields.reader_of(row, axis, producers)
                made, mapper = run, agent
                if who == fields.BY_PASS:
                    made, mapper = pass_of(index, entry)
                elif who == fields.BY_UNKNOWN:
                    made = mapper = None
                lines = [f"<{self._iri('annotation', name, tuple_name, axis)}>"
                         f" a oa:Annotation",
                         f"    ; {self.term('about')} <{about}>",
                         f"    ; {self.term('coordinate')} "
                         f"{ttl_string(axis)}"]
                if made:
                    lines.append(f"    ; prov:wasGeneratedBy <{made}>")
                if state in SCHEMES["ReadingState"]:
                    lines.append(f"    ; {self.term('readingState')} "
                                 f"{self.term(state)}")
                content = row.get(axis)
                body = bodies.get(axis)
                if body:
                    lines.append(f"    ; oa:hasBody <{body}>")
                    if mapper:
                        lines.append(f"    ; {self.term('mappedBy')} "
                                     f"<{mapper}>")
                elif isinstance(content, str) and content.startswith(OUT) \
                        and content[len(OUT):] in SCHEMES[
                            "OutsideVocabulary"]:
                    lines.append(f"    ; {self.term('outsideVocabulary')} "
                                 f"{self.term(content[len(OUT):])}")
                wording = row.get(f"{axis}_raw")
                if wording not in (None, ""):
                    lines.append(f"    ; {self.term('wording')} "
                                 f"{ttl_string(wording)}")
                if row.get(f"{axis}_raw_foreign"):
                    lines.append(f"    ; {self.term('rawForeign')} true")
                source = row.get(f"{axis}_source")
                where = None
                if isinstance(source, (list, tuple)) and len(source) == 2:
                    where = part_of(source[0], source[1])
                target = self._target(where, None, row.get(f"{axis}_quote"))
                if target:
                    lines.append(f"    ; oa:hasTarget {target}")
                out.append("\n".join(lines) + " .")

            verdict = trust.trust(row, transcribed=transcribed,
                                  conflict=bool(value.get("conflict")))
            lines = [f"<{self._iri('trust', name, tuple_name)}> a "
                     f"{self.term('TrustAssessment')}",
                     f"    ; {self.term('about')} <{about}>",
                     f"    ; {self.term('trustLevel')} "
                     f"{self.term(verdict['level'])}",
                     f"    ; {self.term('fromImage')} "
                     f"{str(bool(verdict['image_origin'])).lower()}",
                     f"    ; prov:wasGeneratedBy <{run}>"]
            for reason in verdict["reasons"]:
                concept = _reason_term(reason)
                if concept:
                    lines.append(f"    ; {self.term('trustReason')} "
                                 f"{self.term(concept)}")
                axis = reason.partition(":")[2]
                if axis and f"{axis}_state" in row:
                    lines.append(
                        f"    ; prov:wasDerivedFrom "
                        f"<{self._iri('annotation', name, tuple_name, axis)}>")
            out.append("\n".join(lines) + " .")

            for flag in row.get("flags") or ():
                if flag in _REVIEW:
                    out.append(
                        f"<{self._iri('review', name, tuple_name)}> a "
                        f"{self.term('Review')}\n"
                        f"    ; {self.term('about')} <{about}>\n"
                        f"    ; {self.term('reviewOutcome')} "
                        f"{self.term(_REVIEW[flag])} .")
            if asked not in taken:
                taken.add(asked)
                for decision in decided.get(asked, ()):
                    out.append(self._decision(name, tuple_name, about,
                                              decision))
                    self.decisions += 1
        # On one line: a name with a line break in it would end the
        # comment, and what follows would be read as statements.
        self.parts.append(f"# {' '.join(str(name).split())}\n"
                          + "\n".join(out) + "\n")
        self.documents += 1
        self.values += len(values)

    def write(self, path) -> Optional[Path]:
        """Write what was collected; nothing collected, nothing written."""
        if not self.parts:
            return None
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.header() + "\n" + "\n".join(self.parts),
                        encoding="utf-8")
        return path


def read_stamp(jsonl_dir, name: str) -> dict:
    """The stamp beside a document's harvest, or {}."""
    path = Path(jsonl_dir) / f"{name}.stamp.json"
    try:
        found = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return found if isinstance(found, dict) else {}
